name: jobr
description: ""
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  lyte_studios_flutter_ui:
    git:
      url: https://github.com/LYTE-studios/lyte_studios_flutter_ui
      ref: main

  # NAVIGATION
  go_router: ^14.2.3
  flutter_svg_provider: ^1.0.7
  url_launcher: ^6.3.1
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.16
  dio: ^5.0.0
  flutter_secure_storage: ^8.0.0
  logger: ^2.5.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/images/background/
    - assets/images/icons/
    - assets/images/logos/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter.ttf
