name: jobr
description: ""
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+31

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3

  lyte_studios_flutter_ui:
    git:
      url: https://github.com/LYTE-studios/lyte_studios_flutter_ui
      ref: main

  # NAVIGATION
  go_router: ^14.2.3
  flutter_svg_provider: ^1.0.7
  flutter_launcher_icons: ^0.14.2
  url_launcher: ^6.3.1
  cupertino_icons: ^1.0.8
  flutter_chat_ui: ^1.6.15
  uuid: ^4.5.1
  mime: ^2.0.0
  flutter_svg: ^2.0.16
  dio: ^5.0.0
  flutter_secure_storage: ^10.0.0-beta.4
  logger: ^2.5.0
  file_picker: ^8.1.6
  readmore: ^3.0.0
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  image_picker: ^1.1.2
  flutter_web_auth: ^0.6.0
  flutter_facebook_auth: ^6.0.4
  # modal_bottom_sheet: ^3.0.0    # Removed this line
  intl: ^0.17.0  # or the latest version

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.7
  riverpod_generator: ^2.3.3

flutter:

  uses-material-design: true
  assets:
    - assets/images/background/
    - assets/images/icons/
    - assets/images/jobs/
    - assets/images/logos/
    - assets/images/recruteren/
    - assets/images/images/
    - assets/images/
  


  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter_18pt-Regular.ttf
        - asset: assets/fonts/Inter_18pt-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter_18pt-Italic.ttf
          style: italic
        - asset: assets/fonts/Inter_18pt-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Inter_18pt-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter.ttf
