name: jobr
description: ""
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+10

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  lyte_studios_flutter_ui:
    git:
      url: https://github.com/LYTE-studios/lyte_studios_flutter_ui
      ref: main

  # NAVIGATION
  go_router: ^14.2.3
  flutter_svg_provider: ^1.0.7
  flutter_launcher_icons: ^0.13.1
  url_launcher: ^6.3.1
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.16
  dio: ^5.0.0
  flutter_secure_storage: ^8.0.0
  logger: ^2.5.0
  file_picker: ^8.0.6
  readmore: ^3.0.0

dependency_overrides:
  file_picker: 8.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/images/background/
    - assets/images/icons/
    - assets/images/logos/
    - assets/images/recruteren/
    - assets/images/images/
    - assets/images/
  


  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter_18pt-Regular.ttf
        - asset: assets/fonts/Inter_18pt-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter_18pt-Italic.ttf
          style: italic
        - asset: assets/fonts/Inter_18pt-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Inter_18pt-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter.ttf
