name: Build and Deploy to TestFlight

on:
  pull_request_review:
    types:
      - submitted
jobs:
  build:
    name: Build and Deploy Flutter App to TestFlight
    runs-on: macos-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Check approvals
        id: check-approvals
        uses: actions/github-script@v6
        with:
          script: |
            const { data: reviews } = await github.pulls.listReviews({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
            });

            // Count the number of approvals
            const approvals = reviews.filter(review => review.state === "APPROVED").length;
            console.log(`Approvals: ${approvals}`);
            core.setOutput("approvals", approvals);

          result-encoding: string

      - name: Exit if approvals < 1
        if: steps.check-approvals.outputs.approvals < 1
        run: echo "Insufficient approvals. Exiting..."
  
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'
  
      - name: Install Dependencies
        run: flutter pub get
  
      - name: Build iOS Release
        run: |
          flutter build ios --release --no-codesign
  
      - name: Setup Keychain
        run: |
          echo $P12_CERTIFICATE | base64 --decode > certificate.p12
          echo $PROVISIONING_PROFILE | base64 --decode > profile.mobileprovision
          security create-keychain -p "" build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p "" build.keychain
          security import certificate.p12 -P "$P12_PASSWORD" -A
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp profile.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/
  
      - name: Archive with Xcode
        run: |
          xcodebuild -workspace ios/Runner.xcworkspace \
            -scheme Runner \
            -sdk iphoneos \
            -configuration Release \
            -archivePath build/Runner.xcarchive archive \
            DEVELOPMENT_TEAM=${{ secrets.APPLE_TEAM_ID }}
  
      - name: Export IPA
        run: |
          xcodebuild -exportArchive \
            -archivePath build/Runner.xcarchive \
            -exportOptionsPlist ios/ExportOptions.plist \
            -exportPath build/Runner.ipa
  
      - name: 'Upload app to TestFlight'
        uses: apple-actions/upload-testflight-build@v1
        with: 
          app-path: 'path/to/application.ipa' 
          issuer-id: ${{ secrets.APPSTORE_ISSUER_ID }}
          api-key-id: ${{ secrets.APPSTORE_API_KEY_ID }}
          api-private-key: ${{ secrets.APPSTORE_API_PRIVATE_KEY }
