name: Build and Deploy to TestFlight

on:
  push:
    branches:
      - release/*
jobs:
  build:
    name: Build and Deploy Flutter App to TestFlight
    runs-on: macos-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.27.1
      - run: flutter --version
  
      - name: Install Dependencies
        run: flutter pub get
  
      - name: Setup Keychain
        run: |
          echo ${{ secrets.P12_CERTIFICATE }} | base64 --decode > certificate.p12
          echo ${{ secrets.PROVISIONING_PROFILE }} | base64 --decode > profile.mobileprovision
          security create-keychain -p "" build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p "" build.keychain
          security import certificate.p12 -P "${{ secrets.P12_PASSWORD }}" -A
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp profile.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/

      - name: Build IPA
        run: |
          flutter build ipa --export-options-plist=ios/ExportOptions.plist --output build/Runner.ipa
  
      - name: 'Upload app to TestFlight'
        uses: apple-actions/upload-testflight-build@v1
        with: 
          app-path: 'build/Runner.ipa' 
          issuer-id: ${{ secrets.APPLE_ISSUER_ID }}
          api-key-id: ${{ secrets.APPLE_KEY_ID }}
          api-private-key: ${{ secrets.APPLE_PRIVATE_KEY }}
